# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

aliases:
  - &restore-key
    keys:
      - v1-dependencies-{{ checksum "yarn.lock" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-
  - &save-cache
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "yarn.lock" }}

version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:10.14.2'
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache: *restore-key
      - run: yarn install --frozen-lockfile --non-interactive
      - save_cache: *save-cache

      # run tests!
      - run: yarn test

  release:
    docker:
      - image: 'circleci/node:10.14.2'
    steps:
      - checkout
      - restore_cache: *restore-key
      - run:
          name: 'Release'
          command: 'yarn semantic-release'

workflows:
  version: 2
  build_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
